name: agroalert_ai_plus_app
description: "AgroAlert AI+ - L'assistant agricole intelligent pour les producteurs"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.1.0
  image_picker: ^1.1.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^12.0.0
  dio: ^5.4.3+1
  cached_network_image: ^3.3.1
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/